"""
================================================================================
 AI Workload Performance Analyzer
 --------------------------------------------------------------------------
 Course      : DSA01 - Computer Organization / OOP based Systems Modelling
 Assignment  : Smart AI Research Data Center - Pipeline, Cache & I/O Analyzer
 --------------------------------------------------------------------------
 The application simulates a five-stage processor pipeline (IF, ID, EX, MEM,
 WB) for an image-processing instruction workload, analyzes hierarchical
 cache (L1, L2, L3) behaviour for the LOAD/STORE addresses generated by that
 workload, compares Interrupt-driven I/O and DMA for loading the image
 dataset, and finally combines all three sub-systems into one consolidated
 performance report that identifies the dominant bottleneck.

 Concepts demonstrated: classes & objects, single/multi-level inheritance,
 polymorphism (operator & method overriding), constructors, custom
 exception handling, file handling (JSON in / text+JSON out) and core data
 structures (lists, dicts, deques, sets).
================================================================================
"""

from __future__ import annotations

import json
import os
from abc import ABC, abstractmethod
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Optional, Tuple


# =============================================================================
# SECTION 1 : CUSTOM EXCEPTIONS
# =============================================================================
class WorkloadAnalyzerError(Exception):
    """Base exception for every error raised inside this application."""


class InvalidJobFileError(WorkloadAnalyzerError):
    """Raised when the input workload file is missing / malformed."""


class InvalidInstructionError(WorkloadAnalyzerError):
    """Raised when an instruction record does not have the required fields."""


class CacheConfigurationError(WorkloadAnalyzerError):
    """Raised when a cache level is configured with invalid parameters."""


class IOConfigurationError(WorkloadAnalyzerError):
    """Raised when I/O / DMA parameters are invalid (e.g. zero transfer rate)."""


# =============================================================================
# SECTION 2 : DOMAIN MODEL  (Instruction / Job)
# =============================================================================
@dataclass
class Instruction:
    """Represents one processor instruction issued while processing an image."""
    inst_id: str
    operation: str                 # LOAD, STORE, ADD, SUB, MUL, BRANCH, NOP ...
    src_regs: List[str] = field(default_factory=list)
    dest_reg: Optional[str] = None
    mem_address: Optional[int] = None

    def __post_init__(self):
        if not self.inst_id or not self.operation:
            raise InvalidInstructionError(
                f"Instruction is missing an id/operation: {self}"
            )
        self.operation = self.operation.upper()

    def is_memory_op(self) -> bool:
        return self.operation in ("LOAD", "STORE")

    def is_branch(self) -> bool:
        return self.operation == "BRANCH"

    def __str__(self) -> str:
        return (f"{self.inst_id}:{self.operation} "
                f"src={self.src_regs} dst={self.dest_reg} mem={self.mem_address}")


@dataclass
class ImageJob:
    """Represents one image-processing job submitted to the AI data center."""
    job_id: str
    num_images: int
    image_size_kb: float
    instructions: List[Instruction]

    @classmethod
    def from_dict(cls, data: dict) -> "ImageJob":
        try:
            instructions = [
                Instruction(
                    inst_id=i["inst_id"],
                    operation=i["operation"],
                    src_regs=i.get("src_regs", []),
                    dest_reg=i.get("dest_reg"),
                    mem_address=i.get("mem_address"),
                )
                for i in data["instructions"]
            ]
            return cls(
                job_id=data["job_id"],
                num_images=int(data["num_images"]),
                image_size_kb=float(data["image_size_kb"]),
                instructions=instructions,
            )
        except KeyError as exc:
            raise InvalidJobFileError(f"Missing required field: {exc}") from exc


# =============================================================================
# SECTION 3 : ABSTRACT BASE FOR ALL ANALYZERS  (demonstrates inheritance)
# =============================================================================
class BaseAnalyzer(ABC):
    """Common contract shared by Pipeline, Cache and I/O analyzers."""

    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def run(self):
        """Execute the analysis and return a result dict."""
        raise NotImplementedError

    @abstractmethod
    def summary(self) -> str:
        """Return a short, human-readable summary line (polymorphism)."""
        raise NotImplementedError


# =============================================================================
# SECTION 4 : FIVE-STAGE PIPELINE SIMULATOR
# =============================================================================
class PipelineSimulator(BaseAnalyzer):
    STAGES = ("IF", "ID", "EX", "MEM", "WB")

    def __init__(self, instructions: List[Instruction], clock_period_ns: float = 1.0):
        super().__init__("Pipeline Hazard Analyzer")
        self.instructions = instructions
        self.clock_period_ns = clock_period_ns
        self.result: Dict = {}

    # ---- hazard detection -------------------------------------------------
    def _detect_data_hazards(self) -> List[Tuple[str, str]]:
        """RAW hazard: instruction i's source register was written by one of
        the previous two instructions still in the pipeline (classic 5-stage
        forwarding window)."""
        hazards = []
        for idx, inst in enumerate(self.instructions):
            window = self.instructions[max(0, idx - 2):idx]
            for prev in window:
                if prev.dest_reg and prev.dest_reg in inst.src_regs:
                    hazards.append((prev.inst_id, inst.inst_id))
        return hazards

    def _detect_control_hazards(self) -> List[str]:
        return [inst.inst_id for inst in self.instructions if inst.is_branch()]

    def _detect_structural_hazards(self) -> List[Tuple[str, str]]:
        """Two consecutive MEM-stage instructions (LOAD/STORE) contending for
        the single memory port is treated as a structural hazard."""
        hazards = []
        for idx in range(1, len(self.instructions)):
            cur, prev = self.instructions[idx], self.instructions[idx - 1]
            if cur.is_memory_op() and prev.is_memory_op():
                hazards.append((prev.inst_id, cur.inst_id))
        return hazards

    # ---- main run -----------------------------------------------------------
    def run(self) -> Dict:
        n = len(self.instructions)
        data_hazards = self._detect_data_hazards()
        control_hazards = self._detect_control_hazards()
        structural_hazards = self._detect_structural_hazards()

        stall_cycles = len(data_hazards) * 1          # 1-cycle forwarding stall
        flush_cycles = len(control_hazards) * 2        # 2-cycle branch flush
        structural_stalls = len(structural_hazards) * 1

        ideal_cycles = n + len(self.STAGES) - 1         # no-hazard pipeline fill
        total_cycles = ideal_cycles + stall_cycles + flush_cycles + structural_stalls

        cpi = round(total_cycles / n, 3) if n else 0
        execution_time_ns = round(total_cycles * self.clock_period_ns, 3)
        non_pipelined_cycles = n * len(self.STAGES)
        speedup = round(non_pipelined_cycles / total_cycles, 3) if total_cycles else 0

        self.result = {
            "instructions": n,
            "data_hazards": data_hazards,
            "control_hazards": control_hazards,
            "structural_hazards": structural_hazards,
            "stall_cycles": stall_cycles,
            "flush_cycles": flush_cycles,
            "structural_stall_cycles": structural_stalls,
            "total_cycles": total_cycles,
            "cpi": cpi,
            "execution_time_ns": execution_time_ns,
            "non_pipelined_cycles": non_pipelined_cycles,
            "speedup": speedup,
        }
        return self.result

    def summary(self) -> str:
        r = self.result
        return (f"Pipeline: {r['instructions']} instr | CPI={r['cpi']} | "
                f"cycles={r['total_cycles']} | speed-up={r['speedup']}x")


# =============================================================================
# SECTION 5 : HIERARCHICAL CACHE SIMULATOR (L1 -> L2 -> L3 -> Main Memory)
# =============================================================================
class CacheLevel:
    """A single direct-mapped cache level."""

    def __init__(self, name: str, size_kb: int, block_size_b: int, latency_cycles: int):
        if size_kb <= 0 or block_size_b <= 0 or latency_cycles < 0:
            raise CacheConfigurationError(f"Invalid configuration for cache level {name}")
        self.name = name
        self.size_bytes = size_kb * 1024
        self.block_size_b = block_size_b
        self.num_lines = max(1, self.size_bytes // self.block_size_b)
        self.latency_cycles = latency_cycles
        self.lines: Dict[int, int] = {}   # line_index -> tag
        self.hits = 0
        self.misses = 0

    def access(self, address: int) -> bool:
        block_no = address // self.block_size_b
        line_index = block_no % self.num_lines
        tag = block_no // self.num_lines
        if self.lines.get(line_index) == tag:
            self.hits += 1
            return True
        self.lines[line_index] = tag
        self.misses += 1
        return False

    @property
    def accesses(self) -> int:
        return self.hits + self.misses

    @property
    def hit_ratio(self) -> float:
        return round(self.hits / self.accesses, 4) if self.accesses else 0.0


class CacheAnalyzer(BaseAnalyzer):
    def __init__(self, addresses: List[int], cache_cfg: List[dict], main_mem_latency: int = 100):
        super().__init__("Hierarchical Cache Analyzer")
        self.addresses = addresses
        self.levels = [
            CacheLevel(c["name"], c["size_kb"], c["block_size_b"], c["latency_cycles"])
            for c in cache_cfg
        ]
        self.main_mem_latency = main_mem_latency
        self.result: Dict = {}

    def run(self) -> Dict:
        main_mem_accesses = 0
        total_latency = 0

        for addr in self.addresses:
            for level in self.levels:
                hit = level.access(addr)
                total_latency += level.latency_cycles
                if hit:
                    break
            else:
                main_mem_accesses += 1
                total_latency += self.main_mem_latency

        total_accesses = len(self.addresses) if self.addresses else 1
        amat = round(total_latency / total_accesses, 3)

        per_level = {}
        for level in self.levels:
            per_level[level.name] = {
                "accesses": level.accesses,
                "hits": level.hits,
                "misses": level.misses,
                "hit_ratio": level.hit_ratio,
                "miss_ratio": round(1 - level.hit_ratio, 4) if level.accesses else 0.0,
            }

        self.result = {
            "total_memory_accesses": len(self.addresses),
            "main_memory_accesses": main_mem_accesses,
            "average_memory_access_time_cycles": amat,
            "levels": per_level,
        }
        return self.result

    def summary(self) -> str:
        r = self.result
        l1 = r["levels"].get("L1", {})
        return (f"Cache: {r['total_memory_accesses']} accesses | "
                f"L1 hit-ratio={l1.get('hit_ratio', 0)} | AMAT={r['average_memory_access_time_cycles']} cycles")


# =============================================================================
# SECTION 6 : I/O TRANSFER ANALYZER (Interrupt-driven vs DMA)  -- polymorphism
# =============================================================================
class IOTransferStrategy(ABC):
    def __init__(self, total_data_kb: float, transfer_rate_kbps: float, num_requests: int):
        if transfer_rate_kbps <= 0 or num_requests <= 0:
            raise IOConfigurationError("Transfer rate and request count must be positive")
        self.total_data_kb = total_data_kb
        self.transfer_rate_kbps = transfer_rate_kbps
        self.num_requests = num_requests

    @abstractmethod
    def transfer_time_ms(self) -> float: ...

    @abstractmethod
    def cpu_interventions(self) -> int: ...

    @abstractmethod
    def cpu_utilization_percent(self) -> float: ...


class InterruptDrivenIO(IOTransferStrategy):
    OVERHEAD_MS_PER_INTERRUPT = 0.05   # context-switch / ISR overhead

    def transfer_time_ms(self) -> float:
        base = (self.total_data_kb / self.transfer_rate_kbps) * 1000
        return round(base + self.num_requests * self.OVERHEAD_MS_PER_INTERRUPT, 3)

    def cpu_interventions(self) -> int:
        return self.num_requests            # CPU interrupted for every request

    def cpu_utilization_percent(self) -> float:
        busy = self.num_requests * self.OVERHEAD_MS_PER_INTERRUPT
        return round(min(100.0, (busy / self.transfer_time_ms()) * 100), 2)


class DMAIO(IOTransferStrategy):
    SETUP_MS_PER_REQUEST = 0.01          # CPU only sets up / ends the DMA burst

    def transfer_time_ms(self) -> float:
        base = (self.total_data_kb / self.transfer_rate_kbps) * 1000
        return round(base + self.num_requests * self.SETUP_MS_PER_REQUEST * 0.2, 3)

    def cpu_interventions(self) -> int:
        return 2                             # one setup + one completion signal only

    def cpu_utilization_percent(self) -> float:
        busy = self.num_requests * self.SETUP_MS_PER_REQUEST
        return round(min(100.0, (busy / self.transfer_time_ms()) * 100), 2)


class IOAnalyzer(BaseAnalyzer):
    def __init__(self, total_data_kb: float, transfer_rate_kbps: float, num_requests: int):
        super().__init__("I/O & DMA Comparator")
        self.interrupt_io = InterruptDrivenIO(total_data_kb, transfer_rate_kbps, num_requests)
        self.dma_io = DMAIO(total_data_kb, transfer_rate_kbps, num_requests)
        self.result: Dict = {}

    def run(self) -> Dict:
        interrupt_stats = {
            "transfer_time_ms": self.interrupt_io.transfer_time_ms(),
            "cpu_interventions": self.interrupt_io.cpu_interventions(),
            "cpu_utilization_percent": self.interrupt_io.cpu_utilization_percent(),
        }
        dma_stats = {
            "transfer_time_ms": self.dma_io.transfer_time_ms(),
            "cpu_interventions": self.dma_io.cpu_interventions(),
            "cpu_utilization_percent": self.dma_io.cpu_utilization_percent(),
        }
        more_efficient = "DMA" if dma_stats["transfer_time_ms"] <= interrupt_stats["transfer_time_ms"] \
            and dma_stats["cpu_utilization_percent"] <= interrupt_stats["cpu_utilization_percent"] else "Interrupt-driven"

        self.result = {
            "interrupt_driven": interrupt_stats,
            "dma": dma_stats,
            "more_efficient_method": more_efficient,
        }
        return self.result

    def summary(self) -> str:
        r = self.result
        return (f"I/O: Interrupt={r['interrupt_driven']['transfer_time_ms']}ms "
                f"vs DMA={r['dma']['transfer_time_ms']}ms -> {r['more_efficient_method']} preferred")


# =============================================================================
# SECTION 7 : PERFORMANCE REPORT GENERATOR (aggregation / composition)
# =============================================================================
class PerformanceReportGenerator:
    def __init__(self, job: ImageJob, pipeline_result: dict, cache_result: dict, io_result: dict):
        self.job = job
        self.pipeline_result = pipeline_result
        self.cache_result = cache_result
        self.io_result = io_result

    def _identify_bottleneck(self) -> str:
        scores = {}
        # Higher CPI (relative to ideal 1.0) => pipeline stress
        scores["Pipeline (hazards/stalls)"] = self.pipeline_result["cpi"] - 1.0
        # Higher AMAT => cache stress (normalized against L1 latency baseline of 1)
        scores["Cache (memory hierarchy)"] = self.cache_result["average_memory_access_time_cycles"] / 10
        # Higher CPU utilization on the *faster* I/O method still stresses CPU
        io = self.io_result
        io_stress = min(io["interrupt_driven"]["cpu_utilization_percent"],
                         io["dma"]["cpu_utilization_percent"]) / 100
        scores["I/O (data transfer)"] = io_stress
        return max(scores, key=scores.get)

    def build(self) -> Dict:
        bottleneck = self._identify_bottleneck()
        return {
            "job_id": self.job.job_id,
            "generated_on": datetime.now().isoformat(timespec="seconds"),
            "num_images": self.job.num_images,
            "image_size_kb": self.job.image_size_kb,
            "pipeline": self.pipeline_result,
            "cache": self.cache_result,
            "io": self.io_result,
            "major_bottleneck": bottleneck,
        }

    def print_report(self, report: Dict) -> None:
        print("=" * 78)
        print(f" AI WORKLOAD PERFORMANCE REPORT  |  Job: {report['job_id']}")
        print("=" * 78)
        print(f"Images processed        : {report['num_images']}")
        print(f"Image size (KB)          : {report['image_size_kb']}")
        print("-" * 78)
        p = report["pipeline"]
        print("[1] PIPELINE ANALYSIS")
        print(f"    Instructions          : {p['instructions']}")
        print(f"    Data hazards (RAW)    : {len(p['data_hazards'])} -> {p['data_hazards']}")
        print(f"    Control hazards       : {len(p['control_hazards'])} -> {p['control_hazards']}")
        print(f"    Structural hazards    : {len(p['structural_hazards'])} -> {p['structural_hazards']}")
        print(f"    Stall/Flush cycles    : {p['stall_cycles']} / {p['flush_cycles']} "
              f"(+{p['structural_stall_cycles']} structural)")
        print(f"    Total cycles          : {p['total_cycles']}")
        print(f"    CPI                   : {p['cpi']}")
        print(f"    Execution time (ns)   : {p['execution_time_ns']}")
        print(f"    Speed-up vs unpipelined: {p['speedup']}x")
        print("-" * 78)
        c = report["cache"]
        print("[2] CACHE ANALYSIS")
        for lvl, stats in c["levels"].items():
            print(f"    {lvl:4s} -> accesses={stats['accesses']:3d} hits={stats['hits']:3d} "
                  f"misses={stats['misses']:3d} hit-ratio={stats['hit_ratio']}")
        print(f"    Main memory accesses  : {c['main_memory_accesses']}")
        print(f"    Avg memory access time: {c['average_memory_access_time_cycles']} cycles")
        print("-" * 78)
        io = report["io"]
        print("[3] I/O & DMA ANALYSIS")
        print(f"    Interrupt-driven      : {io['interrupt_driven']}")
        print(f"    DMA                   : {io['dma']}")
        print(f"    More efficient method : {io['more_efficient_method']}")
        print("-" * 78)
        print(f"MAJOR PERFORMANCE BOTTLENECK : {report['major_bottleneck']}")
        print("=" * 78)


# =============================================================================
# SECTION 8 : FILE HANDLING HELPERS
# =============================================================================
def load_job_from_file(path: str) -> ImageJob:
    if not os.path.exists(path):
        raise InvalidJobFileError(f"Input file not found: {path}")
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as exc:
        raise InvalidJobFileError(f"Malformed JSON in {path}: {exc}") from exc
    return ImageJob.from_dict(data), data


def save_report(report: Dict, out_path: str) -> None:
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)


# =============================================================================
# SECTION 9 : DRIVER / MAIN
# =============================================================================
def main():
    input_path = os.path.join(os.path.dirname(__file__), "sample_workload.json")
    output_path = os.path.join(os.path.dirname(__file__), "performance_report.json")

    try:
        job, raw = load_job_from_file(input_path)

        # --- 1. Pipeline analysis --------------------------------------
        pipeline = PipelineSimulator(job.instructions, clock_period_ns=1.0)
        pipeline_result = pipeline.run()

        # --- 2. Cache analysis (addresses from LOAD/STORE only) --------
        addresses = [i.mem_address for i in job.instructions if i.is_memory_op() and i.mem_address is not None]
        cache_cfg = raw["cache_config"]
        cache = CacheAnalyzer(addresses, cache_cfg, main_mem_latency=raw.get("main_memory_latency_cycles", 100))
        cache_result = cache.run()

        # --- 3. I/O analysis ---------------------------------------------
        io_cfg = raw["io_config"]
        total_data_kb = job.num_images * job.image_size_kb
        io = IOAnalyzer(total_data_kb, io_cfg["transfer_rate_kbps"], io_cfg["num_requests"])
        io_result = io.run()

        # --- 4. Consolidated report ---------------------------------------
        generator = PerformanceReportGenerator(job, pipeline_result, cache_result, io_result)
        report = generator.build()
        generator.print_report(report)
        save_report(report, output_path)
        print(f"\nFull JSON report saved to: {output_path}")

        for analyzer_summary in (pipeline.summary(), cache.summary(), io.summary()):
            print("  >", analyzer_summary)

    except WorkloadAnalyzerError as exc:
        print(f"[ERROR] {type(exc).__name__}: {exc}")
    except Exception as exc:  # safety net for any unexpected error
        print(f"[UNEXPECTED ERROR] {exc}")


if __name__ == "__main__":
    main()
